language: node_js
notifications:
- kaiocoutrim@gmail.com
node_js:
- 0.10.25
services:
- mongodb
env:
  global:
  - NODE_ENV: test
addons:
  sauce_connect: true
before_install:
- npm install -g bower@1.3.12
- npm install -g grunt-cli@0.1
- npm install -g karma-cli@0.0
- npm install -g protractor@1.5
- webdriver-manager update
- bower install
before_script:
- grunt minifica
script:
- karma start config/karma.config.js --single-run --browsers PhantomJS
before_deploy:
- git config --global user.email 'travis@travis-ci.com'
- git config --global user.name 'Travis CI'
- git checkout $TRAVIS_BRANCH
- git add --all
- git commit -am "Travis Commit"
deploy:
  provider: openshift
  user: kaiocoutrim@gmail.com
  password:
    secure: eFNXIQb7x05ixXhugscFHsrwIkZ80494W2GezlQKdPr2ApAPFCiLStQKmjsV6ttkdeYkWy3kmUV9D8cdjZAYIdVA0muG6KTFXmRLLM9sF2HJPGojOP4JAV28jId70JT5cTcr/TxUuGKGuqYKKuiaQpRaRSAvi8AcviQm2DbWFEU=
  app: contatooh
  domain: maranhao
  on:
    repo: caiocutrim/contactooh